frontend:
  base-url: https://gratilo.com

stripe:
  success-url: "https://gratilo.com/pay/success?session_id={CHECKOUT_SESSION_ID}"
  cancel-url: https://gratilo.com/pay/cancelled
  sandbox-payouts: true
