package com.tipster.user.service;
import com.tipster.user.api.*; import com.tipster.user.domain.*; import com.tipster.user.repository.*; import io.micronaut.context.annotation.Value; import jakarta.inject.Singleton; import jakarta.transaction.Transactional; import java.time.OffsetDateTime; import java.util.*;
@Singleton public class PoolService {
 private final PoolRepository pools; private final PoolMemberRepository members; private final UserRepository users; private final EmailSendService mail; private final String baseUrl;
 public PoolService(PoolRepository pools,PoolMemberRepository members,UserRepository users,EmailSendService mail,@Value("${frontend.base-url:`http://localhost:3000`}") String baseUrl){this.pools=pools;this.members=members;this.users=users;this.mail=mail;this.baseUrl=baseUrl;}
 public String publicPoolName(UUID owner){return pools.findByOwnerId(owner).map(PoolEntity::getName).orElse(null);}
 @Transactional public PoolResponses.Pool mine(UUID owner){ var p=pools.findByOwnerId(owner).orElse(null); if(p!=null) ensureOwnerMember(p); return toResponse(p); }
 @Transactional public List<PoolResponses.Pool> memberships(UUID userId){var result=new ArrayList<PoolResponses.Pool>(); for(var m: members.findByUserId(userId)){ if(!m.getStatus().equals("DECLINED")){ pools.findById(m.getPoolId()).filter(p -> !p.getOwnerId().equals(userId)).map(this::toResponse).ifPresent(result::add); } } return result; }
 @Transactional public PoolResponses.Distribution distribution(UUID owner){var p=pools.findByOwnerId(owner).orElse(null);if(p==null)return null;ensureOwnerMember(p);var result=new ArrayList<PoolResponses.DistributionMember>();for(var m:members.findByPoolId(p.getId())){if(!"ACTIVE".equalsIgnoreCase(m.getStatus())||!m.isActive())continue;var u=users.findById(m.getUserId()).orElse(null);if(u!=null)result.add(new PoolResponses.DistributionMember(u.getId(),((u.getFirstName()==null?"":u.getFirstName())+" "+(u.getLastName()==null?"":u.getLastName())).trim(),u.getEmail(),m.getSharePercent(),m.isActive(),u.isStripeOnboardingCompleted()));}return new PoolResponses.Distribution(p.getId(),p.getName(),result);}
 @Transactional public PoolResponses.Pool create(UUID owner,String name){ if(pools.findByOwnerId(owner).isPresent()) throw new IllegalStateException("Du hast bereits einen Pool."); var p=new PoolEntity();p.setId(UUID.randomUUID());p.setOwnerId(owner);p.setName(name);p.setCreatedAt(OffsetDateTime.now());p=pools.save(p); ensureOwnerMember(p); return toResponse(p); }
 @Transactional public PoolResponses.Pool invite(UUID owner,UUID poolId,String email){var p=owned(owner,poolId);ensureOwnerMember(p);var u=users.findByEmail(email.toLowerCase()).orElseThrow(()->new IllegalArgumentException("Kein Benutzer mit dieser E-Mail-Adresse gefunden.")); if(u.getId().equals(owner))throw new IllegalArgumentException("Der Pool-Besitzer kann nicht eingeladen werden."); if(members.findByPoolIdAndUserId(poolId,u.getId()).isPresent())throw new IllegalArgumentException("Dieser Benutzer ist bereits im Pool."); var m=new PoolMemberEntity();m.setId(UUID.randomUUID());m.setPoolId(poolId);m.setUserId(u.getId());m.setSharePercent(members.findByPoolId(poolId).stream().noneMatch(existing->!"DECLINED".equals(existing.getStatus()))?100:0);m.setStatus("INVITED");m.setActive(true);m.setInvitationToken(UUID.randomUUID().toString()+UUID.randomUUID());m.setInvitationExpiresAt(OffsetDateTime.now().plusDays(1));m.setCreatedAt(OffsetDateTime.now());members.save(m);mail.sendText(u.getEmail(),"Pool-Einladung bei Gratilo", "Du wurdest zu einem Trinkgeld-Pool eingeladen. Öffne diesen Link, um die Einladung anzunehmen oder abzulehnen:\n\n"+baseUrl+"/pool/invitations/"+m.getInvitationToken());return toResponse(p); }
 @Transactional public PoolResponses.Pool respond(String token,UUID userId,boolean accept){var m=members.findByInvitationToken(token).orElseThrow(()->new IllegalArgumentException("Einladung ist ungültig."));if(!m.getUserId().equals(userId))throw new IllegalArgumentException("Diese Einladung gehört zu einem anderen Benutzer.");if(m.getInvitationExpiresAt()!=null&&m.getInvitationExpiresAt().isBefore(OffsetDateTime.now()))throw new IllegalArgumentException("Diese Einladung ist abgelaufen.");m.setStatus(accept?"ACTIVE":"DECLINED");m.setRespondedAt(OffsetDateTime.now());members.update(m);var p=pools.findById(m.getPoolId()).orElseThrow();var owner=users.findById(p.getOwnerId()).orElse(null);var user=users.findById(userId).orElse(null);if(owner!=null&&user!=null)mail.sendText(owner.getEmail(),"Pool-Einladung beantwortet",user.getEmail()+" hat die Einladung zu deinem Pool '"+p.getName()+"' "+(accept?"angenommen.":"abgelehnt."));return toResponse(p);}
 @Transactional public PoolResponses.Pool resend(UUID owner,UUID poolId,UUID memberId){var p=owned(owner,poolId);var m=members.findById(memberId).orElseThrow();if(!m.getPoolId().equals(poolId))throw new IllegalArgumentException("Mitglied gehört nicht zu diesem Pool.");var u=users.findById(m.getUserId()).orElseThrow();m.setStatus("INVITED");m.setInvitationToken(UUID.randomUUID().toString()+UUID.randomUUID());m.setInvitationExpiresAt(OffsetDateTime.now().plusDays(1));m.setRespondedAt(null);members.update(m);mail.sendText(u.getEmail(),"Neue Pool-Einladung bei Gratilo","Deine Einladung wurde verlängert. Öffne diesen Link innerhalb von 24 Stunden:\n\n"+baseUrl+"/pool/invitations/"+m.getInvitationToken());return toResponse(p);}
 @Transactional public PoolResponses.Pool setActive(UUID owner,UUID poolId,UUID memberId,boolean active){var p=owned(owner,poolId);ensureOwnerMember(p);var m=members.findById(memberId).orElseThrow();if(!m.getPoolId().equals(poolId))throw new IllegalArgumentException("Mitglied gehört nicht zu diesem Pool.");if(m.getUserId().equals(owner))throw new IllegalArgumentException("Der Pool-Besitzer kann nicht deaktiviert werden.");m.setActive(active);members.update(m);return toResponse(p);}
 @Transactional public PoolResponses.Pool updateShares(UUID owner,UUID poolId,List<PoolRequests.ShareValue> values){var p=owned(owner,poolId);ensureOwnerMember(p);var poolMembers=members.findByPoolId(poolId);var supplied=new HashMap<UUID,Double>();for(var value:values){if(value.sharePercent()<0||value.sharePercent()>100)throw new IllegalArgumentException("Jeder Anteil muss zwischen 0 und 100 % liegen.");supplied.put(value.memberId(),value.sharePercent());}double total=0;for(var m:poolMembers){if("DECLINED".equals(m.getStatus()))continue;double share=supplied.getOrDefault(m.getId(),m.getSharePercent());if(share<0||share>100)throw new IllegalArgumentException("Jeder Anteil muss zwischen 0 und 100 % liegen.");total+=share;}if(total>100.001)throw new IllegalArgumentException("Die Anteile dürfen zusammen höchstens 100 % ergeben.");for(var m:poolMembers){if(supplied.containsKey(m.getId())){m.setSharePercent(supplied.get(m.getId()));members.update(m);}}return toResponse(p);}
 @Transactional public PoolResponses.Pool updateShare(UUID owner,UUID poolId,UUID memberId,double share){var p=owned(owner,poolId);ensureOwnerMember(p);var m=members.findById(memberId).orElseThrow();if(!m.getPoolId().equals(poolId))throw new IllegalArgumentException("Mitglied gehört nicht zu diesem Pool."); double used=members.findByPoolId(poolId).stream().filter(other->!other.getId().equals(memberId)&&!"DECLINED".equals(other.getStatus())).mapToDouble(PoolMemberEntity::getSharePercent).sum(); if(used+share>100.001)throw new IllegalArgumentException("Die Anteile dürfen zusammen höchstens 100 % ergeben.");m.setSharePercent(share);members.update(m);return toResponse(p);}
 @Transactional public PoolResponses.Pool remove(UUID owner,UUID poolId,UUID memberId){var p=owned(owner,poolId);ensureOwnerMember(p);var m=members.findById(memberId).orElseThrow(); if(!m.getPoolId().equals(poolId))throw new IllegalArgumentException("Mitglied gehört nicht zu diesem Pool."); if(m.getUserId().equals(owner))throw new IllegalArgumentException("Der Pool-Besitzer kann nicht entfernt werden."); users.findById(m.getUserId()).ifPresent(u->mail.sendText(u.getEmail(),"Aus einem Pool entfernt", "Du wurdest aus dem Pool '"+p.getName()+"' entfernt.")); members.deleteById(memberId);return toResponse(p);}
 @Transactional public PoolResponses.Pool setMemberActive(UUID userId,UUID memberId,boolean active){var m=members.findById(memberId).orElseThrow();if(!m.getUserId().equals(userId))throw new IllegalArgumentException("Keine Berechtigung für diese Mitgliedschaft.");var p=pool(m.getPoolId());m.setActive(active);members.update(m);notifyOwner(p,userId,active?"aktiviert":"deaktiviert");return toResponse(p);}
 @Transactional public PoolResponses.Pool removeMember(UUID userId,UUID memberId){var m=members.findById(memberId).orElseThrow();if(!m.getUserId().equals(userId))throw new IllegalArgumentException("Keine Berechtigung für diese Mitgliedschaft.");var p=pool(m.getPoolId());members.deleteById(memberId);notifyOwner(p,userId,"gelöscht");return toResponse(p);}
 @Transactional public void removeUser(UUID userId){
  for(var membership:new ArrayList<>(members.findByUserId(userId))){
   var p=pools.findById(membership.getPoolId()).orElse(null); if(p==null) continue;
   if(!p.getOwnerId().equals(userId)){ notifyOwner(p,userId,"gelöscht"); members.deleteById(membership.getId()); }
  }
  var ownedPool=pools.findByOwnerId(userId).orElse(null); if(ownedPool!=null){ for(var m:members.findByPoolId(ownedPool.getId())){ users.findById(m.getUserId()).ifPresent(u->mail.sendText(u.getEmail(),"Pool gelöscht", "Der Pool '"+ownedPool.getName()+"' wurde gelöscht, weil der Besitzer sein Gratilo-Konto geschlossen hat.")); } pools.deleteById(ownedPool.getId()); }
 }
 @Transactional public void delete(UUID owner,UUID poolId){var p=owned(owner,poolId);for(var m:members.findByPoolId(poolId)){users.findById(m.getUserId()).ifPresent(u->mail.sendText(u.getEmail(),"Pool gelöscht", "Der Pool '"+p.getName()+"' wurde vom Besitzer gelöscht."));}pools.deleteById(poolId);}
 private void ensureOwnerMember(PoolEntity p){ if(members.findByPoolIdAndUserId(p.getId(),p.getOwnerId()).isEmpty()){var owner=new PoolMemberEntity();owner.setId(UUID.randomUUID());owner.setPoolId(p.getId());owner.setUserId(p.getOwnerId());owner.setSharePercent(100);owner.setStatus("ACTIVE");owner.setActive(true);owner.setCreatedAt(OffsetDateTime.now());members.save(owner);} }
 private void notifyOwner(PoolEntity p,UUID userId,String action){var owner=users.findById(p.getOwnerId()).orElse(null);var user=users.findById(userId).orElse(null);if(owner!=null&&user!=null)mail.sendText(owner.getEmail(),"Pool-Mitgliedschaft aktualisiert",user.getEmail()+" hat seine Mitgliedschaft im Pool '"+p.getName()+"' "+action+".");}
 private PoolEntity owned(UUID owner,UUID id){var p=pool(id);if(!p.getOwnerId().equals(owner))throw new IllegalArgumentException("Keine Berechtigung für diesen Pool.");return p;} private PoolEntity pool(UUID id){return pools.findById(id).orElseThrow(()->new IllegalArgumentException("Pool nicht gefunden."));}
 private PoolResponses.Pool toResponse(PoolEntity p){if(p==null)return null;var list=new ArrayList<PoolResponses.Member>();for(var m:members.findByPoolId(p.getId())){var u=users.findById(m.getUserId()).orElse(null);list.add(new PoolResponses.Member(m.getId(),m.getUserId(),u==null?"":u.getEmail(),u==null?"":((u.getFirstName()==null?"":u.getFirstName())+" "+(u.getLastName()==null?"":u.getLastName())).trim(),m.getSharePercent(),m.getStatus(),m.isActive(),m.getInvitationExpiresAt(),m.getInvitationToken()));}return new PoolResponses.Pool(p.getId(),p.getName(),p.getOwnerId(),list);}
}
