name: Docker Build PR
'on':
  pull_request:
    branches:
    - main
permissions:
  contents: read
jobs:
  docker-build-pr:
    strategy:
      matrix:
        service:
        - frontend
        - user-service
        - payment-service
    uses: ./.github/workflows/005_docker_build.yml
    with:
      service: ${{ matrix.service }}
      registry: ecr
      aws_region: ${{ vars.AWS_REGION || 'eu-north-1' }}
      aws_account_id: ${{ vars.AWS_ACCOUNT_ID }}
      push: false
