name: Release (Create Tag)
'on':
  workflow_dispatch:
    inputs:
      release_type:
        description: Select release type
        required: true
        type: choice
        options:
        - patch
        - minor
        - major
permissions:
  contents: write
  packages: write
jobs:
  create-tag:
    uses: ./.github/workflows/006_release_tag.yml
    with:
      release_type: ${{ inputs.release_type }}
  build-and-push-ecr:
    name: Build and Push ECR Images
    needs: create-tag
    strategy:
      matrix:
        service:
        - frontend
        - user-service
        - payment-service
    uses: ./.github/workflows/005_docker_build.yml
    with:
      service: ${{ matrix.service }}
      registry: ecr
      aws_region: ${{ vars.AWS_REGION || 'eu-central-1' }}
      aws_account_id: ${{ vars.AWS_ACCOUNT_ID }}
      image_tag: ${{ needs.create-tag.outputs.version }}
      push_latest: true
    secrets: inherit
  deploy-frontend-prd:
    name: Deploy Frontend PRD
    needs:
    - create-tag
    - build-and-push-ecr
    uses: ./.github/workflows/007_deploy_ecs.yml
    with:
      cluster: tipster-cluster
      service_name: tipster-prd-frontend
      task_definition_family: tipster-prd-frontend
      container_name: frontend
      image: ${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION || 'eu-central-1' }}.amazonaws.com/tipster/frontend:${{ needs.create-tag.outputs.version }}
      aws_region: ${{ vars.AWS_REGION || 'eu-central-1' }}
      production: true
    secrets: inherit
  deploy-user-service-prd:
    name: Deploy User Service PRD
    needs:
    - create-tag
    - build-and-push-ecr
    uses: ./.github/workflows/007_deploy_ecs.yml
    with:
      cluster: tipster-cluster
      service_name: tipster-prd-user-service
      task_definition_family: tipster-prd-user-service
      container_name: user-service
      image: ${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION || 'eu-central-1' }}.amazonaws.com/tipster/user-service:${{ needs.create-tag.outputs.version }}
      aws_region: ${{ vars.AWS_REGION || 'eu-central-1' }}
      production: true
    secrets: inherit
  deploy-payment-service-prd:
    name: Deploy Payment Service PRD
    needs:
    - create-tag
    - build-and-push-ecr
    uses: ./.github/workflows/007_deploy_ecs.yml
    with:
      cluster: tipster-cluster
      service_name: tipster-prd-payment-service
      task_definition_family: tipster-prd-payment-service
      container_name: payment-service
      image: ${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION || 'eu-central-1' }}.amazonaws.com/tipster/payment-service:${{ needs.create-tag.outputs.version }}
      aws_region: ${{ vars.AWS_REGION || 'eu-central-1' }}
      production: true
    secrets: inherit
concurrency:
  group: tipster-release
  cancel-in-progress: false
